--- 
abstract: Client component for TCP JSONRPC
author: Daisuke Murase <typester@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: JSONRPC-Transport-TCP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  IO::Socket::INET: 0
  JSON::Any: 0
version: 0.01
